name: Python application test with github action

on: 
  push:
  workflow_dispatch:

jobs:
 build:

   runs-on: ubuntu-latest

   steps:
      - uses: actions/checkout@v2
      - name: Set up python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run:  |
          make install
        working-directory: test-make-lint-githubaction
      
      - name: Lint with pylint
        run: |
          make lint
        working-directory: test-make-lint-githubaction
      
      - name: Test with pytest
        run: |
          make test
        working-directory: test-make-lint-githubaction
      - name: format code
        run: |
          make format
        working-directory: test-make-lint-githubaction
          
